// <auto-generated />
using System;
using InsightVault.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace InsightVault.API.Data.Migrations
{
    [DbContext(typeof(InsightVaultDbContext))]
    [Migration("20260603055701_HardenChatMessageContextIntegrity")]
    partial class HardenChatMessageContextIntegrity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InsightVault.API.Domain.Entities.AiJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("InputPayload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_payload")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("job_type");

                    b.Property<string>("OutputPayload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("output_payload")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_jobs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_ai_jobs_created_at");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_ai_jobs_created_by_id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_ai_jobs_document_id");

                    b.HasIndex("JobType")
                        .HasDatabaseName("ix_ai_jobs_job_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ai_jobs_status");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_ai_jobs_workspace_id");

                    b.ToTable("ai_jobs", (string)null);
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_session_id");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ModelName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("model_name");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasAlternateKey("Id", "WorkspaceId")
                        .HasName("ak_chat_messages_id_workspace_id");

                    b.HasIndex("ChatSessionId")
                        .HasDatabaseName("ix_chat_messages_chat_session_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_chat_messages_created_at");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_chat_messages_workspace_id");

                    b.HasIndex("ChatSessionId", "WorkspaceId")
                        .HasDatabaseName("ix_chat_messages_chat_session_id_workspace_id");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.ChatMessageContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChatMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_message_id");

                    b.Property<string>("ContextDisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("context_display_name");

                    b.Property<int>("ContextOrder")
                        .HasColumnType("integer")
                        .HasColumnName("context_order");

                    b.Property<string>("ContextPath")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("context_path");

                    b.Property<string>("ContextType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("context_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<bool>("IncludeSubfolders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("include_subfolders");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_message_contexts");

                    b.HasIndex("ChatMessageId")
                        .HasDatabaseName("ix_chat_message_contexts_chat_message_id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_chat_message_contexts_document_id");

                    b.HasIndex("FolderId")
                        .HasDatabaseName("ix_chat_message_contexts_folder_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_chat_message_contexts_workspace_id");

                    b.HasIndex("ChatMessageId", "ContextOrder")
                        .HasDatabaseName("ix_chat_message_contexts_chat_message_id_context_order");

                    b.HasIndex("ChatMessageId", "WorkspaceId")
                        .HasDatabaseName("ix_chat_message_contexts_chat_message_id_workspace_id");

                    b.HasIndex("DocumentId", "WorkspaceId")
                        .HasDatabaseName("ix_chat_message_contexts_document_id_workspace_id");

                    b.HasIndex("FolderId", "WorkspaceId")
                        .HasDatabaseName("ix_chat_message_contexts_folder_id_workspace_id");

                    b.HasIndex("ChatMessageId", "ContextType", "DocumentId")
                        .IsUnique()
                        .HasDatabaseName("ix_chat_message_contexts_chat_message_id_context_type_document")
                        .HasFilter("document_id IS NOT NULL");

                    b.HasIndex("ChatMessageId", "ContextType", "FolderId")
                        .IsUnique()
                        .HasDatabaseName("ix_chat_message_contexts_chat_message_id_context_type_folder_id")
                        .HasFilter("folder_id IS NOT NULL");

                    b.ToTable("chat_message_contexts", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_message_contexts_context_shape", "(context_type = 'Folder' AND folder_id IS NOT NULL AND document_id IS NULL) OR (context_type = 'Document' AND document_id IS NOT NULL AND folder_id IS NULL)");
                        });
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.ChatMessageSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChatMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_message_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DocumentChunkId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_chunk_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<double?>("SimilarityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("similarity_score");

                    b.Property<string>("Snippet")
                        .HasColumnType("text")
                        .HasColumnName("snippet");

                    b.Property<int>("SourceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("source_order");

                    b.HasKey("Id")
                        .HasName("pk_chat_message_sources");

                    b.HasIndex("ChatMessageId")
                        .HasDatabaseName("ix_chat_message_sources_chat_message_id");

                    b.HasIndex("DocumentChunkId")
                        .HasDatabaseName("ix_chat_message_sources_document_chunk_id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_chat_message_sources_document_id");

                    b.HasIndex("Metadata")
                        .HasDatabaseName("ix_chat_message_sources_metadata");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Metadata"), "gin");

                    b.ToTable("chat_message_sources", (string)null);
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_sessions");

                    b.HasAlternateKey("Id", "WorkspaceId")
                        .HasName("ak_chat_sessions_id_workspace_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_chat_sessions_created_by_id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_chat_sessions_deleted_at");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_chat_sessions_workspace_id");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ExtractedTextHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("extracted_text_hash");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<string>("KeyPoints")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("key_points")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("keywords")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mime_type");

                    b.Property<string>("MinioBucket")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("minio_bucket");

                    b.Property<string>("MinioObjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("minio_object_key");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_file_name");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("text")
                        .HasColumnName("processing_error");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UploadedById")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasAlternateKey("Id", "WorkspaceId")
                        .HasName("ak_documents_id_workspace_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_documents_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_documents_deleted_at");

                    b.HasIndex("FolderId")
                        .HasDatabaseName("ix_documents_folder_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_documents_status");

                    b.HasIndex("UploadedById")
                        .HasDatabaseName("ix_documents_uploaded_by_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_documents_workspace_id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("CharEnd")
                        .HasColumnType("integer")
                        .HasColumnName("char_end");

                    b.Property<int?>("CharStart")
                        .HasColumnType("integer")
                        .HasColumnName("char_start");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("embedding_model");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("NormalizedContent")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("normalized_content");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_document_chunks");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_document_chunks_document_id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_document_chunks_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("FolderId")
                        .HasDatabaseName("ix_document_chunks_folder_id");

                    b.HasIndex("Metadata")
                        .HasDatabaseName("ix_document_chunks_metadata");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Metadata"), "gin");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_document_chunks_workspace_id");

                    b.HasIndex("DocumentId", "ChunkIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_document_chunks_document_id_chunk_index");

                    b.ToTable("document_chunks", (string)null);
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_folder_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_folders");

                    b.HasAlternateKey("Id", "WorkspaceId")
                        .HasName("ak_folders_id_workspace_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_folders_created_by_id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_folders_deleted_at");

                    b.HasIndex("ParentFolderId")
                        .HasDatabaseName("ix_folders_parent_folder_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_folders_workspace_id");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_folders_workspace_id_name")
                        .HasFilter("parent_folder_id IS NULL AND deleted_at IS NULL");

                    b.HasIndex("WorkspaceId", "ParentFolderId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_folders_workspace_id_parent_folder_id_name")
                        .HasFilter("parent_folder_id IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AiJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_job_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<string>("MarkdownContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("markdown_content");

                    b.Property<string>("ModelName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("model_name");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("report_type");

                    b.Property<string>("SourceDocuments")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_documents")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("StructuredResult")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("structured_result")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("AiJobId")
                        .HasDatabaseName("ix_reports_ai_job_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_reports_created_at");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_reports_created_by_id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_reports_deleted_at");

                    b.HasIndex("FolderId")
                        .HasDatabaseName("ix_reports_folder_id");

                    b.HasIndex("ReportType")
                        .HasDatabaseName("ix_reports_report_type");

                    b.HasIndex("SourceDocuments")
                        .HasDatabaseName("ix_reports_source_documents");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SourceDocuments"), "gin");

                    b.HasIndex("StructuredResult")
                        .HasDatabaseName("ix_reports_structured_result");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("StructuredResult"), "gin");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_reports_workspace_id");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("SystemRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("system_role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_id");

                    b.HasIndex("SystemRole")
                        .HasDatabaseName("ix_users_system_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_workspaces_deleted_at");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_workspaces_owner_id");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.WorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("InvitedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("InvitedById")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_id");

                    b.Property<DateTimeOffset?>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_members");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_workspace_members_email");

                    b.HasIndex("InvitedById")
                        .HasDatabaseName("ix_workspace_members_invited_by_id");

                    b.HasIndex("RemovedAt")
                        .HasDatabaseName("ix_workspace_members_removed_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_workspace_members_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_workspace_members_user_id");

                    b.HasIndex("WorkspaceId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_members_workspace_id_email")
                        .HasFilter("removed_at IS NULL");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_members_workspace_id_user_id")
                        .HasFilter("removed_at IS NULL AND user_id IS NOT NULL");

                    b.ToTable("workspace_members", (string)null);
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.AiJob", b =>
                {
                    b.HasOne("InsightVault.API.Domain.Entities.User", "CreatedBy")
                        .WithMany("AiJobs")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ai_jobs_users_created_by_id");

                    b.HasOne("InsightVault.API.Domain.Entities.Document", "Document")
                        .WithMany("AiJobs")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_ai_jobs_documents_document_id");

                    b.HasOne("InsightVault.API.Domain.Entities.Workspace", "Workspace")
                        .WithMany("AiJobs")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_ai_jobs_workspaces_workspace_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Document");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("InsightVault.API.Domain.Entities.ChatSession", "ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId", "WorkspaceId")
                        .HasPrincipalKey("Id", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_chat_sessions_chat_session_id_workspace_id");

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.ChatMessageContext", b =>
                {
                    b.HasOne("InsightVault.API.Domain.Entities.ChatMessage", "ChatMessage")
                        .WithMany("Contexts")
                        .HasForeignKey("ChatMessageId", "WorkspaceId")
                        .HasPrincipalKey("Id", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_message_contexts_chat_messages_chat_message_id_workspa");

                    b.HasOne("InsightVault.API.Domain.Entities.Document", "Document")
                        .WithMany("ChatMessageContexts")
                        .HasForeignKey("DocumentId", "WorkspaceId")
                        .HasPrincipalKey("Id", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_chat_message_contexts_documents_document_id_workspace_id");

                    b.HasOne("InsightVault.API.Domain.Entities.Folder", "Folder")
                        .WithMany("ChatMessageContexts")
                        .HasForeignKey("FolderId", "WorkspaceId")
                        .HasPrincipalKey("Id", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_chat_message_contexts_folders_folder_id_workspace_id");

                    b.Navigation("ChatMessage");

                    b.Navigation("Document");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.ChatMessageSource", b =>
                {
                    b.HasOne("InsightVault.API.Domain.Entities.ChatMessage", "ChatMessage")
                        .WithMany("Sources")
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_message_sources_chat_messages_chat_message_id");

                    b.HasOne("InsightVault.API.Domain.Entities.DocumentChunk", "DocumentChunk")
                        .WithMany("ChatMessageSources")
                        .HasForeignKey("DocumentChunkId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chat_message_sources_document_chunks_document_chunk_id");

                    b.HasOne("InsightVault.API.Domain.Entities.Document", "Document")
                        .WithMany("ChatMessageSources")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_message_sources_documents_document_id");

                    b.Navigation("ChatMessage");

                    b.Navigation("Document");

                    b.Navigation("DocumentChunk");
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.ChatSession", b =>
                {
                    b.HasOne("InsightVault.API.Domain.Entities.User", "CreatedBy")
                        .WithMany("ChatSessions")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chat_sessions_users_created_by_id");

                    b.HasOne("InsightVault.API.Domain.Entities.Workspace", "Workspace")
                        .WithMany("ChatSessions")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_sessions_workspaces_workspace_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.Document", b =>
                {
                    b.HasOne("InsightVault.API.Domain.Entities.Folder", "Folder")
                        .WithMany("Documents")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_folders_folder_id");

                    b.HasOne("InsightVault.API.Domain.Entities.User", "UploadedBy")
                        .WithMany("UploadedDocuments")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_users_uploaded_by_id");

                    b.HasOne("InsightVault.API.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Documents")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_workspaces_workspace_id");

                    b.Navigation("Folder");

                    b.Navigation("UploadedBy");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.DocumentChunk", b =>
                {
                    b.HasOne("InsightVault.API.Domain.Entities.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_chunks_documents_document_id");

                    b.HasOne("InsightVault.API.Domain.Entities.Folder", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_document_chunks_folders_folder_id");

                    b.HasOne("InsightVault.API.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_chunks_workspaces_workspace_id");

                    b.Navigation("Document");

                    b.Navigation("Folder");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.Folder", b =>
                {
                    b.HasOne("InsightVault.API.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedFolders")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_folders_users_created_by_id");

                    b.HasOne("InsightVault.API.Domain.Entities.Folder", "ParentFolder")
                        .WithMany("ChildFolders")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_folders_folders_parent_folder_id");

                    b.HasOne("InsightVault.API.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Folders")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_folders_workspaces_workspace_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("ParentFolder");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.Report", b =>
                {
                    b.HasOne("InsightVault.API.Domain.Entities.AiJob", "AiJob")
                        .WithMany("Reports")
                        .HasForeignKey("AiJobId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_reports_ai_jobs_ai_job_id");

                    b.HasOne("InsightVault.API.Domain.Entities.User", "CreatedBy")
                        .WithMany("Reports")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_reports_users_created_by_id");

                    b.HasOne("InsightVault.API.Domain.Entities.Folder", "Folder")
                        .WithMany("Reports")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_reports_folders_folder_id");

                    b.HasOne("InsightVault.API.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Reports")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reports_workspaces_workspace_id");

                    b.Navigation("AiJob");

                    b.Navigation("CreatedBy");

                    b.Navigation("Folder");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.Workspace", b =>
                {
                    b.HasOne("InsightVault.API.Domain.Entities.User", "Owner")
                        .WithMany("OwnedWorkspaces")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.WorkspaceMember", b =>
                {
                    b.HasOne("InsightVault.API.Domain.Entities.User", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workspace_members_users_invited_by_id");

                    b.HasOne("InsightVault.API.Domain.Entities.User", "User")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_workspace_members_users_user_id");

                    b.HasOne("InsightVault.API.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_workspaces_workspace_id");

                    b.Navigation("InvitedBy");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.AiJob", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.ChatMessage", b =>
                {
                    b.Navigation("Contexts");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.Document", b =>
                {
                    b.Navigation("AiJobs");

                    b.Navigation("ChatMessageContexts");

                    b.Navigation("ChatMessageSources");

                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.DocumentChunk", b =>
                {
                    b.Navigation("ChatMessageSources");
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.Folder", b =>
                {
                    b.Navigation("ChatMessageContexts");

                    b.Navigation("ChildFolders");

                    b.Navigation("Documents");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.User", b =>
                {
                    b.Navigation("AiJobs");

                    b.Navigation("ChatSessions");

                    b.Navigation("CreatedFolders");

                    b.Navigation("OwnedWorkspaces");

                    b.Navigation("Reports");

                    b.Navigation("UploadedDocuments");

                    b.Navigation("WorkspaceMemberships");
                });

            modelBuilder.Entity("InsightVault.API.Domain.Entities.Workspace", b =>
                {
                    b.Navigation("AiJobs");

                    b.Navigation("ChatSessions");

                    b.Navigation("Documents");

                    b.Navigation("Folders");

                    b.Navigation("Members");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
