import type { ReportDto } from '@/types/api-contract'

export const mockReports: ReportDto[] = [
  {
    id: 'report-001',
    workspaceId: 'ws-001',
    folderId: 'folder-001',
    title: 'MVP Feature Summary Report',
    reportType: 'summary_report',
    markdownContent: `# MVP Feature Summary Report

## Executive Summary

InsightVault AI is a collaborative AI-powered knowledge workspace designed for university project teams and research groups. This report summarizes the MVP feature set derived from the project proposal, requirements document, and sprint planning materials.

## Core Features

### 1. Authentication
- Google OAuth login with JWT token management
- System roles: \`user\` and \`admin\`
- No password storage — Google identity is the source of truth

### 2. Shared Workspaces
- Create, edit, and delete workspaces
- Each workspace serves as an isolated knowledge context
- Workspace-level AI system prompt configuration

### 3. Collaboration (Co-work)
| Role | Capabilities |
|------|-------------|
| Owner | Full management, member invitation, role assignment |
| Editor | Upload documents, create folders, use AI features, generate reports |
| Viewer | Read documents, view summaries, read reports |

### 4. Document Management
- **Supported formats**: PDF (text-based), DOCX, TXT, Markdown
- **Storage**: File → MinIO (object storage), Metadata → PostgreSQL
- **Processing pipeline**: Extract → Clean → Chunk → Embed → Store → Summarize

### 5. AI Processing Pipeline
\`\`\`
Upload → Background Job → Extract Text → Chunk (512-1024 tokens)
→ Gemini Embedding → pgvector Storage → Summary Generation
\`\`\`

### 6. RAG Chat
- Scope: Document, Folder, or Workspace level
- Citations with document name, chunk snippet, and similarity score
- Chat session history preserved

### 7. Document Comparison
- Select 2+ documents for AI analysis
- Output: similarities, differences, missing information, conflicts, recommendations
- Results stored as comparison reports

### 8. Report Generation
- Input: single document, folder, or selected documents
- Output: Markdown format report
- Types: summary, comparison, gap analysis, section reports
- No PDF/DOCX export in MVP

## Technology Stack

| Component | Technology |
|-----------|-----------|
| Frontend | React + Vite + TailwindCSS |
| Backend | ASP.NET Core Web API |
| Auth | Google OAuth + JWT |
| Database | PostgreSQL + pgvector |
| File Storage | MinIO |
| AI | Gemini API |
| AI Service | Python |

## Out of Scope
- Realtime editing / cursor presence
- OCR for scanned documents
- Mobile native app
- PDF/DOCX export
- Knowledge graph
- Billing/payment

---

*Generated by InsightVault AI on May 25, 2026*`,
    sourceDocuments: ['doc-001', 'doc-002', 'doc-003'],
    structuredResult: null,
    modelName: 'gemini-1.5-pro',
    createdAt: '2026-05-25T10:30:00Z',
    updatedAt: '2026-05-25T11:00:00Z',
  },
  {
    id: 'report-002',
    workspaceId: 'ws-001',
    folderId: null,
    title: 'Proposal vs Requirement Gap Analysis',
    reportType: 'comparison_report',
    markdownContent: `# Gap Analysis: Proposal v2 vs Requirements

## Analysis Scope
Comparing project vision (Proposal v2.md) with technical specification (Requirement.docx) to identify alignment gaps.

## Key Findings

### ✅ Aligned Areas
1. Authentication model (Google OAuth + JWT)
2. Workspace collaboration with role-based access
3. Document processing pipeline architecture
4. RAG chat implementation approach
5. Admin monitoring requirements

### ⚠️ Gaps Identified

#### Gap 1: Report Generation Scope
- **Proposal**: Lists report generation as "demo-critical" P0 feature
- **Requirement**: Mentions reports exist but lacks specification for types, templates, or user flow
- **Risk**: Team may implement inconsistently without clear spec
- **Action**: Add detailed report generation section to requirements

#### Gap 2: Export Format Boundaries
- **Proposal**: References "PDF export" in demo context
- **Requirement**: Explicitly excludes PDF/DOCX export from MVP
- **Risk**: Stakeholder confusion during demo
- **Action**: Align both documents on export limitations

#### Gap 3: Viewer AI Permissions
- **Proposal**: Implies all workspace members can use AI
- **Requirement**: States viewer "may use AI chat if system allows"
- **Risk**: Ambiguous permission model
- **Action**: Define explicit viewer permissions in requirement

## Recommendations
1. Reconcile report generation specifications across documents
2. Add "Scope Boundaries" appendix to proposal
3. Create permission matrix for all workspace roles
4. Document error handling for each AI job type

---

*Generated by InsightVault AI on May 24, 2026*`,
    sourceDocuments: ['doc-001', 'doc-002'],
    structuredResult: null,
    modelName: 'gemini-1.5-pro',
    createdAt: '2026-05-24T15:00:00Z',
    updatedAt: '2026-05-24T15:10:00Z',
  },
]
