import { AlertCircle, Loader2 } from 'lucide-react'
import { useDocumentExtractedText } from '@/hooks/useDocuments'
import type { DocumentDto } from '@/types/api'

export function DocumentExtractedTextViewer({ document }: { document: DocumentDto }) {
  const { data, isLoading, isError } = useDocumentExtractedText(document.id, true)

  if (isLoading) {
    return (
      <div className="flex min-h-[360px] items-center justify-center rounded-lg border border-border bg-surface-0 text-sm text-muted-foreground">
        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
        Loading extracted document text...
      </div>
    )
  }

  if (isError || !data) {
    return (
      <div className="flex min-h-[320px] flex-col items-center justify-center rounded-lg border border-dashed border-border bg-surface-0 p-8 text-center">
        <AlertCircle className="mb-3 h-6 w-6 text-warning-600" />
        <h2 className="text-sm font-semibold text-foreground">Extracted text is not available yet</h2>
        <p className="mt-2 max-w-sm text-sm leading-6 text-muted-foreground">
          DOCX inline preview uses the processed text generated by the AI pipeline. Wait for processing to complete, then reopen this tab.
        </p>
      </div>
    )
  }

  return (
    <pre className="whitespace-pre-wrap font-mono text-[13px] leading-relaxed text-foreground">
      {data.content}
    </pre>
  )
}
